# Generated by Django 2.1.7 on 2019-02-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='article_address',
            field=models.URLField(),
        ),
    ]
